sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123

  redis:
    host: localhost
    port: 6379
    password: root123
    database: 0

  wechat:
    appid: wx2deef03fb8637c0a
    secret: db7b299c34662f72130c24595040bcb6
